USE hr_db;

SELECT JOB_ID, COUNT(*) FROM EMPLOYEES group by JOB_ID;

SELECT MANAGER_ID, MIN(SALARY) FROM EMPLOYEES group by MANAGER_ID;

SELECT DEPARTMENT_ID, SUM(SALARY) FROM EMPLOYEES group by DEPARTMENT_ID;

SELECT JOB_ID, AVG(SALARY) FROM EMPLOYEES WHERE JOB_ID IN 

(SELECT JOB_ID FROM jobs WHERE JOB_TITLE != "Programmer") 

group by JOB_ID;


SELECT JOB_ID, MAX(SALARY) FROM EMPLOYEES WHERE SALARY >= 4000 group by JOB_ID;

SELECT JOB_ID, MAX(SALARY) FROM EMPLOYEES group by JOB_ID HAVING MAX(SALARY) >= 4000;

SELECT JOB_ID,MAX(SALARY) AS Max_salary FROM hr_db.employees GROUP BY JOB_ID HAVING Max_salary >= 4000;

SELECT DEPARTMENT_ID, AVG(SALARY) FROM EMPLOYEES group by DEPARTMENT_ID HAVING COUNT(*) > 10;

SELECT AVG(SALARY) FROM EMPLOYEES HAVING COUNT(DEPARTMENT_ID) > 10;
