USE hr_db;

SELECT DEPARTMENT_NAME, LOCATION_ID, STREET_ADDRESS, CITY, STATE_PROVINCE, COUNTRY_NAME

FROM departments NATURAL JOIN locations NATURAL JOIN countries;

SELECT FIRST_NAME, LAST_NAME, emp.DEPARTMENT_ID, DEPARTMENT_NAME

FROM employees as emp JOIN departments as dep

ON emp.DEPARTMENT_ID = dep.DEPARTMENT_ID;

SELECT FIRST_NAME, LAST_NAME, JOB_TITLE, employees.DEPARTMENT_ID, DEPARTMENT_NAME FROM departments, employees NATURAL JOIN jobs

WHERE employees.DEPARTMENT_ID = departments.DEPARTMENT_ID AND

LOCATION_ID = (SELECT LOCATION_ID FROM locations WHERE CITY = 'London');

SELECT FIRST_NAME, LAST_NAME, j.JOB_TITLE, d.DEPARTMENT_ID, d.DEPARTMENT_NAME FROM employees as e

JOIN departments as d

ON d.DEPARTMENT_ID = e.DEPARTMENT_ID

JOIN jobs as j

ON e.JOB_ID = j.JOB_ID

JOIN locations as l

ON d.LOCATION_ID = l.LOCATION_ID

WHERE l.CITY = 'London';


SELECT DEPARTMENT_NAME, COUNT(EMPLOYEE_ID) FROM departments, employees

WHERE employees.DEPARTMENT_ID = departments.DEPARTMENT_ID

GROUP BY DEPARTMENT_NAME;

SELECT DEPARTMENT_NAME, COUNT(e.DEPARTMENT_ID) as 'Employees' FROM departments as d

JOIN employees as e

ON e.DEPARTMENT_ID = d.DEPARTMENT_ID

GROUP BY e.DEPARTMENT_ID;

SELECT FIRST_NAME, LAST_NAME, HIRE_DATE FROM employees

WHERE HIRE_DATE >

(SELECT HIRE_DATE FROM employees WHERE LAST_NAME = 'Jones');

SELECT e.FIRST_NAME, e.LAST_NAME, e.HIRE_DATE FROM employees as e

JOIN (SELECT * FROM employees WHERE LAST_NAME = 'Jones') as jones

ON e.HIRE_DATE > jones.HIRE_DATE;