USE hr_db;



SELECT FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES 
WHERE (SALARY NOT BETWEEN 10000 AND 15000) AND DEPARTMENT_ID IN(30, 100);

SELECT FIRST_NAME, LAST_NAME, HIRE_DATE FROM EMPLOYEES WHERE YEAR(HIRE_DATE) = 1987;

SELECT FIRST_NAME FROM EMPLOYEES WHERE FIRST_NAME LIKE "%b%" OR FIRST_NAME LIKE "%c%";

SELECT LAST_NAME, JOB_ID, SALARY FROM EMPLOYEES WHERE JOB_ID IN 

(SELECT JOB_ID FROM JOBS WHERE JOB_TITLE = "Programmer" OR JOB_TITLE = "Shipping Clerk") 

AND SALARY NOT IN (4500, 10000, 15000);

SELECT LAST_NAME, JOB_ID, SALARY FROM hr_db.employees WHERE JOB_ID IN ("SH_CLERK","IT_PROG") AND SALARY NOT IN (4500,10000,15000);

SELECT * FROM EMPLOYEES WHERE LAST_NAME IN ("Blake", "Scott", "King", "Ford");