USE hr_db;

SELECT FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES

WHERE SALARY > (SELECT MAX(SALARY) FROM EMPLOYEES WHERE LAST_NAME = "Bull");

SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES

WHERE DEPARTMENT_ID IN 

(SELECT DEPARTMENT_ID FROM departments WHERE DEPARTMENT_NAME = "IT");

SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES

WHERE JOB_ID IN 

(SELECT JOB_ID FROM jobs WHERE JOB_TITLE LIKE "%Manager%");

SELECT FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES

WHERE SALARY > (SELECT AVG(SALARY) FROM employees);

SELECT FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES

WHERE SALARY IN (SELECT MIN_SALARY FROM jobs WHERE employees.JOB_ID = jobs.JOB_ID);

SELECT FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID FROM employees AS x

WHERE SALARY IN 

(SELECT MIN(SALARY) FROM employees as y
 WHERE x.DEPARTMENT_ID = y.DEPARTMENT_ID);

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, 

(select DEPARTMENT_NAME FROM departments where DEPARTMENT_ID = employees.DEPARTMENT_ID)

AS 'Department name' 
FROM employees;


SELECT * FROM employees order by EMPLOYEE_ID DESC LIMIT 10;